### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by devmuppet** [Azure/dev-box-images#9]
### What happened?

More of a feature request - which isnt an option... can you add a guideline for integration with azure devops? 

If i manage to get it working ill submit a pr lol but i dont have faith in my own ability :)

**Comment by colbylwilliams** [comment]
@devmuppet check out the quickstart in the [az-bake repo](https://github.com/colbylwilliams/az-bake).  az bake is another iteration on this repo that simplifies some of the setup.  When you run the command in the {6th steps](https://github.com/colbylwilliams/az-bake#6-setup-the-repo-for-use-with-az-bake) in a new Azure DevOps repo, az bake will set up the devops pipeline for you.  

After you follow the quickstart in the az-bake repo, you can reference [this fork](https://github.com/colbylwilliams/dev-box-images) as an example of defining the same images in this repo using az bake.

**Comment by devmuppet** [comment]
@colbylwilliams I could kiss you sir 😘

I'll give that a spin today and see how I get on. Really appreciate this dude!!
